// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJHgFWYyvwt6bOwmqlqfdzQafF-Mqu8vA',
    appId: '1:1093034437034:web:38b1d3a90711fc5bc0e3d3',
    messagingSenderId: '1093034437034',
    projectId: 'hire-a-chef-5e1d4',
    authDomain: 'hire-a-chef-5e1d4.firebaseapp.com',
    storageBucket: 'hire-a-chef-5e1d4.appspot.com',
    measurementId: 'G-DJ9S0F1W23',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDbTtRXooAKhnzuIrGOqtgt1mTE8LH2rK0',
    appId: '1:1093034437034:android:8ab36424a477cdc8c0e3d3',
    messagingSenderId: '1093034437034',
    projectId: 'hire-a-chef-5e1d4',
    storageBucket: 'hire-a-chef-5e1d4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqXTpkBpXMeoDif7lchLiW30U_AiFjjsk',
    appId: '1:1093034437034:ios:9e6b6ccb674e6ea6c0e3d3',
    messagingSenderId: '1093034437034',
    projectId: 'hire-a-chef-5e1d4',
    storageBucket: 'hire-a-chef-5e1d4.appspot.com',
    iosClientId: '1093034437034-jp04momjb4313lfkdj9tq00v9an9757u.apps.googleusercontent.com',
    iosBundleId: 'com.example.hireAChef',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqXTpkBpXMeoDif7lchLiW30U_AiFjjsk',
    appId: '1:1093034437034:ios:9e6b6ccb674e6ea6c0e3d3',
    messagingSenderId: '1093034437034',
    projectId: 'hire-a-chef-5e1d4',
    storageBucket: 'hire-a-chef-5e1d4.appspot.com',
    iosClientId: '1093034437034-jp04momjb4313lfkdj9tq00v9an9757u.apps.googleusercontent.com',
    iosBundleId: 'com.example.hireAChef',
  );
}
